from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WEBSITE = ROOT / "website"
PUBLIC_DOC_IDS = [
    "getting-started",
    "cli",
    "python-api",
    "dataset",
    "hs-mx-nico",
    "data-model",
    "sources",
    "provenance",
    "release-process",
    "reproducibility",
    "verify-release",
    "production-certification",
]


def test_docusaurus_source_scaffold_is_isolated_from_python_runtime():
    required = (
        "package.json",
        "tsconfig.json",
        "docusaurus.config.ts",
        "sidebars.ts",
        "src/css/custom.css",
        "src/pages/index.tsx",
        "src/pages/index.module.css",
    )
    assert [path for path in required if not (WEBSITE / path).is_file()] == []
    assert not (WEBSITE / "docs").exists()


def test_docusaurus_package_matches_verified_3_10_2_template_family():
    payload = json.loads((WEBSITE / "package.json").read_text(encoding="utf-8"))
    docusaurus_packages = {
        **{
            key: value
            for key, value in payload["dependencies"].items()
            if key.startswith("@docusaurus/")
        },
        **{
            key: value
            for key, value in payload["devDependencies"].items()
            if key.startswith("@docusaurus/")
        },
    }
    assert docusaurus_packages
    assert set(docusaurus_packages.values()) == {"3.10.2"}
    assert payload["engines"]["node"] == ">=20.0"
    assert payload["scripts"]["build"] == "docusaurus build"
    assert payload["scripts"]["typecheck"] == "tsc --noEmit"


def test_docusaurus_config_uses_root_docs_and_bilingual_project_pages_route():
    text = (WEBSITE / "docusaurus.config.ts").read_text(encoding="utf-8")
    required = (
        "url: 'https://jccontrerasg08-cpu.github.io'",
        "baseUrl: '/arancel-mx/'",
        "defaultLocale: 'es'",
        "locales: ['es', 'en']",
        "htmlLang: 'es-MX'",
        "htmlLang: 'en-US'",
        "path: '../docs'",
        "exclude: ['superpowers/**', 'operations/**']",
        "blog: false",
        "type: 'localeDropdown'",
        "onBrokenLinks: 'throw'",
    )
    assert [value for value in required if value not in text] == []


def test_sidebar_is_explicit_and_excludes_internal_docs():
    text = (WEBSITE / "sidebars.ts").read_text(encoding="utf-8")
    positions = [text.index(f"'{doc_id}'") for doc_id in PUBLIC_DOC_IDS]
    assert positions == sorted(positions)
    assert "autogenerated" not in text
    assert "superpowers" not in text
    assert "operations" not in text


def test_generated_docusaurus_paths_are_ignored_but_lockfile_is_not():
    text = (ROOT / ".gitignore").read_text(encoding="utf-8")
    for path in (
        "website/node_modules/",
        "website/build/",
        "website/.docusaurus/",
    ):
        assert path in text
    assert "website/package-lock.json" not in text
