export const PUBLIC_ROUTES = Object.freeze([
  { path: '/', label: 'Home' },
  { path: '/app', label: 'Explorer' },
  { path: '/product', label: 'Explorer alias' },
  { path: '/app/record/:code', label: 'Verified record' },
  { path: '/chapters', label: 'Chapters' },
  { path: '/changes', label: 'Changes' },
  { path: '/moa', label: 'MOA guide' },
  { path: '/moa-guide', label: 'MOA guide alias' },
  { path: '/wiki', label: 'Wiki' },
  { path: '/glossary', label: 'Glossary' },
  { path: '/trade-context', label: 'Trade context' },
  { path: '/documentation', label: 'Documentation' },
  { path: '/trust', label: 'Trust' },
  { path: '/records', label: 'My records' },
  { path: '/trade', label: 'Trade desk' },
  { path: '/features', label: 'Product features' },
  { path: '/pricing', label: 'Data releases' },
  { path: '/analytics', label: 'Release analytics' },
  { path: '/community', label: 'Community' },
]);
